name: Publish Package

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Get Version
        id: version
        uses: battila7/get-version-action@v2

      - name: Pack
        run: dotnet pack --configuration Release /p:Version=${{ steps.version.outputs.version-without-v }} --output .

      - name: Push to NuGet
        run: dotnet nuget push *.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_API_KEY} --skip-duplicate
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            *.nupkg
          name: Release ${{ steps.version.outputs.version }}
          body: |
            Release of version ${{ steps.version.outputs.version }}
            
            ### Changes
            - Please list changes here
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}