name: Publish Package

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write # Add this line for release creation
  packages: write # If you're also publishing packages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Get Version
        id: version
        shell: bash
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "version-without-v=$VERSION" >> $GITHUB_OUTPUT

      - name: Pack
        run: dotnet pack --configuration Release /p:Version=${{ steps.version.outputs.version-without-v }} --output .

      - name: Push to NuGet
        run: |
          for attempt in {1..3}; do
            if dotnet nuget push *.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_API_KEY} --skip-duplicate; then
              exit 0
            fi
            echo "Attempt $attempt failed. Waiting 30 seconds before retry..."
            sleep 30
          done
          exit 1
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "*.nupkg"
          name: Release ${{ steps.version.outputs.version }}
          body: |
            Release of version ${{ steps.version.outputs.version }}
            
            ### Changes
            - Please list changes here
          draft: true
          allowUpdates: true